version: "1.29.2"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - clips_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: clips_vol
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Password

volumes:
  clips_vol:
